apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mongo
  name: mongo
spec:
  ports:
  - name: 27018-27017
    port: 27018
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo
  type: ClusterIP
status:
  loadBalancer: {}