apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
    serviceMonitorSelector: prometheus
  name: todoservicemonitor
spec:
  endpoints:
  - interval: 10s
    port: http
    path: /metrics
  namespaceSelector:
    # matchNames:
    # - prometheus
  selector:
    matchLabels:
      app.kubernetes.io/name: todo-todo-app
      app.kubernetes.io/name: todo-app