apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'efk'
spec:
  project: default
  source:
    repoURL: 'https://github.com/yardenmev/GitOps-bootcamp-portfolio'
    path: efk
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    syncOptions:
      - ServerSideApply=true