apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'todo'
spec:
  project: default
  source:
    repoURL: 'https://github.com/yardenmev/GitOps-bootcamp-portfolio'
    path: todo-chart
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    syncOptions:
    - ServerSideApply=true